### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by esotericsean** [bendem/OreBroadcast#26]
Doesn't seem to work at all anymore on 1.10 -- any chance for an update?

**Comment by bendem** [comment]
OreBroadcast is a bukkit plugin. If memory serves right, that stopped in 1.7. So no, I'm not planning on updating it.

The plugin is opensource ([GPLv3](https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29)) tho, so anyone is free to update it, I just personally won't.

**Comment by esotericsean** [comment]
Spigot took over bukkit and has been updating it since 1.8. It's alive and well. OreBroadcaster was actually working up until 1.9, but finally stopped working on 1.10.

I'll see if our developer can take a look here and update it.

**Comment by mbax** [comment]
> Spigot took over bukkit 

Objection! Inaccuracy!

Spigot maintains their own fork, while still ignoring US copyright law. Not the same as taking over, in any sense. Wouldn't be possible without Microsoft's blessing, and I doubt their legal team wants to step into that mess because it could lead to forced open sourcing of the server code. 

Your issue ticket posted here doesn't describe what you've tested, what you've observed, or any error messages (or lack of messages) in the server log. Entirely useless issue.

**Comment by esotericsean** [comment]
They don't. You have to compile it yourself with BuildTools. They don't distribute compiled versions.

And this ticket _is_ valuable because now you know that it is no longer working! That's a good start and is as much as I know. Now that I've said it's no longer working, the developer is aware of it. Sure, more information would be better. But there is still value in simply posting that it has one.

**Comment by mbax** [comment]
I have nothing to do with this plugin, @esotericsean , I'm just here to point out when you're wrong. The distribution of the compiled binary was not the only issue, but I know that's their major talking point despite that not being the reason they can't be on Github anymore. 

A single person saying "it isn't working" is not remotely valuable. @bendem needs actual, useful information to base fixes on. Not "I can't make it work"
